version: '3.8'

services:
  # Audio Processing Backend (Flask)
  audio-backend:
    build: ./rapidmixer_2_0/backend
    ports:
      - "5000:5000"
    environment:
      - DEBUG=false
      - PORT=5000
      - UPLOAD_FOLDER=/app/uploads
      - SEPARATED_FOLDER=/app/separated
      - MAX_CONTENT_LENGTH=52428800
    volumes:
      - ./rapidmixer_2_0/backend/uploads:/app/uploads
      - ./rapidmixer_2_0/backend/separated:/app/separated
    restart: unless-stopped

  # User Management Backend (Node.js)
  user-backend:
    build: ./rapid-mixer-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: unless-stopped
    depends_on:
      - audio-backend

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - audio-backend
      - user-backend
    restart: unless-stopped
    profiles:
      - production