name: rapidmixer_2_0
description: A Flutter application for audio separation and mixing.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Layout
  sizer: ^2.0.15
  
  # HTTP requests
  http: ^1.1.0
  dio: ^5.3.2
  
  # Web support
  web: ^0.3.0
  flutter_web_plugins:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/